rule Shellcode_Carberp_API_Hashing {
    meta:
        author = "Jeremy Humble"
        date = "2021-11-23"
        description = "Detects known Carberp hashes of windows API names. Also used in Bazar"
        references = "https://raw.githubusercontent.com/pan-unit42/public_tools/master/teslacrypt/deobfuscate_api_calls.py"

    strings:
        $LoadLibraryA_le              = {26 80 AC C8}
        $LoadLibraryA_be              = {C8 AC 80 26}
        $LoadLibraryW_le              = {30 80 AC C8}
        $LoadLibraryW_be              = {C8 AC 80 30}
        $LoadLibraryExA_le            = {6A 8E 08 20}
        $LoadLibraryExA_be            = {20 08 8E 6A}
        $LoadLibraryExW_le            = {7C 8E 08 20}
        $LoadLibraryExW_be            = {20 08 8E 7C}
        $GetProcAddress_le            = {EE EA C0 1F}
        $GetProcAddress_be            = {1F C0 EA EE}
        $VirtualAlloc_le              = {FE 6A 7A 69}
        $VirtualAlloc_be              = {69 7A 6A FE}
        $VirtualAllocEx_le            = {A6 B8 BF 9A}
        $VirtualAllocEx_be            = {9A BF B8 A6}
        $VirtualFree_le               = {5F 70 35 3A}
        $VirtualFree_be               = {3A 35 70 5F}
        $VirtualQuery_le              = {65 24 58 6A}
        $VirtualQuery_be              = {6A 58 24 65}
        $VirtualQueryEx_le            = {6E 78 19 09}
        $VirtualQueryEx_be            = {09 19 78 6E}
        $VirtualProtect_le            = {5A 6F DE A9}
        $VirtualProtect_be            = {A9 DE 6F 5A}
        $VirtualProtectEx_le          = {8F 88 D6 9B}
        $VirtualProtectEx_be          = {9B D6 88 8F}
        $CloseHandle_le               = {D5 B0 3E 72}
        $CloseHandle_be               = {72 3E B0 D5}
        $GlobalAlloc_le               = {71 A1 5E 72}
        $GlobalAlloc_be               = {72 5E A1 71}
        $GlobalFree_le                = {C8 39 03 24}
        $GlobalFree_be                = {24 03 39 C8}
        $CreateFileA_le               = {14 F1 F8 08}
        $CreateFileA_be               = {08 F8 F1 14}
        $CreateFileW_le               = {02 F1 F8 08}
        $CreateFileW_be               = {08 F8 F1 02}
        $WriteFile_le                 = {C3 D1 3F 0F}
        $WriteFile_be                 = {0F 3F D1 C3}
        $GetCurrentDirectoryA_le      = {CE 15 07 C8}
        $GetCurrentDirectoryA_be      = {C8 07 15 CE}
        $WriteProcessMemory_le        = {35 BF A0 BE}
        $WriteProcessMemory_be        = {BE A0 BF 35}
        $CreateRemoteThread_le        = {B3 74 18 E6}
        $CreateRemoteThread_be        = {E6 18 74 B3}
        $ReadFile_le                  = {6B E1 7F 48}
        $ReadFile_be                  = {48 7F E1 6B}
        $GetModuleHandleA_le          = {62 67 8D A4}
        $GetModuleHandleA_be          = {A4 8D 67 62}
        $GetModuleHandleW_le          = {74 67 8D A4}
        $GetModuleHandleW_be          = {A4 8D 67 74}
        $Sleep_le                     = {F5 72 99 3D}
        $Sleep_be                     = {3D 99 72 F5}
        $CreateProcessA_le            = {C7 8A 31 46}
        $CreateProcessA_be            = {46 31 8A C7}
        $CreateProcessW_le            = {D1 8A 31 46}
        $CreateProcessW_be            = {46 31 8A D1}
        $ReadProcessMemory_le         = {61 A7 00 9D}
        $ReadProcessMemory_be         = {9D 00 A7 61}
        $OpenProcess_le               = {9D 29 A4 99}
        $OpenProcess_be               = {99 A4 29 9D}
        $Process32First_le            = {90 8C F7 19}
        $Process32First_be            = {19 F7 8C 90}
        $Process32Next_le             = {1E EA 30 C9}
        $Process32Next_be             = {C9 30 EA 1E}
        $CreateToolhelp32Snapshot_le  = {4F D1 C1 5B}
        $CreateToolhelp32Snapshot_be  = {5B C1 D1 4F}
        $WinExec_le                   = {AD 6D BF E8}
        $WinExec_be                   = {E8 BF 6D AD}
        $FindResourceA_le             = {0C 06 FE 08}
        $FindResourceA_be             = {08 FE 06 0C}
        $LoadResource_le              = {8B BD 10 1A}
        $LoadResource_be              = {1A 10 BD 8B}
        $CreateEventA_le              = {DC 50 5A 8D}
        $CreateEventA_be              = {8D 5A 50 DC}
        $GetTickCount_le              = {52 01 26 69}
        $GetTickCount_be              = {69 26 01 52}
        $GetThreadContext_le          = {2F E0 1D AA}
        $GetThreadContext_be          = {AA 1D E0 2F}
        $SetThreadContext_le          = {2F C8 1D AA}
        $SetThreadContext_be          = {AA 1D C8 2F}
        $HeapAlloc_le                 = {67 B0 50 55}
        $HeapAlloc_be                 = {55 50 B0 67}
        $LocalAlloc_le                = {A1 B0 5C 72}
        $LocalAlloc_be                = {72 5C B0 A1}
        $send_le                      = {64 77 79 0E}
        $send_be                      = {0E 79 77 64}
        $connect_le                   = {8A FE D8 ED}
        $connect_be                   = {ED D8 FE 8A}
        $gethostbyname_le             = {C6 18 43 F4}
        $gethostbyname_be             = {F4 43 18 C6}
        $NtCreateSection_le           = {8B 60 6F 6E}
        $NtCreateSection_be           = {6E 6F 60 8B}
        $NtOpenSection_le             = {38 AB A9 5F}
        $NtOpenSection_be             = {5F A9 AB 38}
        $ZwMapViewOfSection_le        = {3C 9A 4D 59}
        $ZwMapViewOfSection_be        = {59 4D 9A 3C}
        $ZwAllocateVirtualMemory_le   = {E4 A9 4A 59}
        $ZwAllocateVirtualMemory_be   = {59 4A A9 E4}
        $ZwWriteVirtualMemory_le      = {23 AF E7 EE}
        $ZwWriteVirtualMemory_be      = {EE E7 AF 23}
        $ZwProtectVirtualMemory_le    = {3E C6 36 38}
        $ZwProtectVirtualMemory_be    = {38 36 C6 3E}
        $LdrLoadDll_le                = {34 05 74 78}
        $LdrLoadDll_be                = {78 74 05 34}
        $LdrGetDllHandle_le           = {6A 7C 28 7E}
        $LdrGetDllHandle_be           = {7E 28 7C 6A}
        $LdrGetProcedureAddress_le    = {75 28 3C 32}
        $LdrGetProcedureAddress_be    = {32 3C 28 75}
        $ZwSetContextThread_le        = {6F FE E2 62}
        $ZwSetContextThread_be        = {62 E2 FE 6F}
        $ShellExecuteW_le             = {8F C8 0B 57}
        $ShellExecuteW_be             = {57 0B C8 8F}
        $ShellExecuteA_le             = {99 C8 0B 57}
        $ShellExecuteA_be             = {57 0B C8 99}
        $ShellExecuteExA_le           = {83 69 27 F2}
        $ShellExecuteExA_be           = {F2 27 69 83}
        $ShellExecuteExW_le           = {95 69 27 F2}
        $ShellExecuteExW_be           = {F2 27 69 95}
        $InternetConnectA_le          = {3E 8D 61 BE}
        $InternetConnectA_be          = {BE 61 8D 3E}
        $InternetConnectW_le          = {28 8D 61 BE}
        $InternetConnectW_be          = {BE 61 8D 28}
        $HttpOpenRequestA_le          = {2F 00 10 15}
        $HttpOpenRequestA_be          = {15 10 00 2F}
        $HttpOpenRequestW_le          = {39 00 10 15}
        $HttpOpenRequestW_be          = {15 10 00 39}
        $HttpSendRequestA_le          = {6A 85 13 9F}
        $HttpSendRequestA_be          = {9F 13 85 6A}
        $HttpSendRequestW_le          = {7C 85 13 9F}
        $HttpSendRequestW_be          = {9F 13 85 7C}
        $InternetOpenA_le             = {D7 3D 59 08}
        $InternetOpenA_be             = {08 59 3D D7}
        $InternetOpenUrlA_le          = {66 BD 7D B8}
        $InternetOpenUrlA_be          = {B8 7D BD 66}
        $InternetReadFile_le          = {62 29 21 1A}
        $InternetReadFile_be          = {1A 21 29 62}
        $InternetReadFileExA_le       = {64 38 52 2C}
        $InternetReadFileExA_be       = {2C 52 38 64}
        $InternetReadFileExW_le       = {72 38 52 2C}
        $InternetReadFileExW_be       = {2C 52 38 72}
    condition:
        filesize < 5MB and 3 of them or
        filesize < 10MB and 4 of them or
        filesize < 25MB and 5 of them or
        filesize < 100MB and 7 of them or
        filesize < 200MB and 12 of them or
        15 of them
}
